version: '1.0'
services:
  backend:
    container_name: patient_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    container_name: patient_database
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'patient_hub'
      MONGO_INITDB_ROOT_PASSWORD: '0GjTKZn8auAd!6qywzbBaSunKGYtM4T0m8ZGt6I!Lks'

volumes:
  mongodb_data: